//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPro_CardManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevPro_CardManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x20 Dark
        ///0x40 Divine
        ///0x1 Earth
        ///0x4 Fire
        ///0x10 Light
        ///0x2 Water
        ///0x8 Wind .
        /// </summary>
        internal static string cardattributes {
            get {
                return ResourceManager.GetString("cardattributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 TCG
        ///1 OCG
        ///3 OCG/TCG
        ///4 Anime.
        /// </summary>
        internal static string cardformats {
            get {
                return ResourceManager.GetString("cardformats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffffff All
        ///0x1 Warrior
        ///0x2 Spellcaster
        ///0x4 Fairy
        ///0x8 Fiend
        ///0x10 Zombie
        ///0x20 Machine
        ///0x40 Aqua
        ///0x80 Pyro
        ///0x100 Rock
        ///0x200 Winged Beast
        ///0x400 Plant
        ///0x800 Insect
        ///0x1000 Thunder
        ///0x2000 Dragon
        ///0x4000 Beast
        ///0x8000 Beast Warrior
        ///0x10000 Dinosaur
        ///0x20000 Fish
        ///0x40000 Seaserpent
        ///0x80000 Reptile
        ///0x100000 Psychic
        ///0x200000 DevineBeast
        ///0x400000 Creator God
        ///0x800000 Wyrm.
        /// </summary>
        internal static string cardraces {
            get {
                return ResourceManager.GetString("cardraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !setname 0x1 Ally of Justice
        ///!setname 0x2 Genex
        ///!setname 0x1002 R－Genex
        ///!setname 0x2002 Genex Ally
        ///!setname 0x4 Amazoness
        ///!setname 0x5 Arcana Force
        ///!setname 0x6 Dark World
        ///!setname 0x7 Ancient Gear
        ///!setname 0x8 HERO
        ///!setname 0x3008 Elemental HERO
        ///!setname 0x6008 Evil HERO
        ///!setname 0xc008 Destiny HERO
        ///!setname 0x5008 Vision HERO
        ///!setname 0xa008 Masked HERO
        ///!setname 0x9 Neos
        ///!setname 0xa Lswarm
        ///!setname 0x100a Steelswarm
        ///!setname 0xb Infernity
        ///!setname 0xc Alien
        ///!setname 0xd Saber
        ///!setname [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string setname {
            get {
                return ResourceManager.GetString("setname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unknown {
            get {
                object obj = ResourceManager.GetObject("unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
